# Generated by Django 4.0.6 on 2022-07-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employers',
            new_name='Employee',
        ),
    ]
